# Generated by Django 4.1.1 on 2022-11-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.TextField(max_length=50)),
                ('flight_no', models.TextField(max_length=50)),
                ('departure_city', models.TextField(max_length=50)),
                ('arrival_city', models.TextField(max_length=50)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('e_seats', models.TextField(max_length=50)),
                ('b_seats', models.TextField(max_length=50)),
                ('price', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='pictures/')),
            ],
        ),
    ]
