# Generated by Django 4.1.1 on 2022-11-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0005_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='b_seats',
            new_name='no_of_seats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='e_seats',
        ),
    ]
