# Generated by Django 4.1.1 on 2022-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0006_rename_b_seats_flight_no_of_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('date', models.DateField()),
                ('message', models.TextField(max_length=50)),
            ],
        ),
    ]
